pipeline:
  name: testing-react
  identifier: testingreact
  projectIdentifier: testing
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: github
        build: <+input>
  stages:
    - stage:
        name: Buildand Push
        identifier: Buildand_Push
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          platform:
            os: Windows
            arch: Amd64
          runtime:
            type: Docker
            spec: {}
          execution:
            steps:
              - step:
                  type: BuildAndPushDockerRegistry
                  name: BuildAndPushDockerRegistry_1
                  identifier: BuildAndPushDockerRegistry_1
                  spec:
                    connectorRef: Docker_connector
                    repo: docker.io/venkatasridhar301298/first-harness-image
                    tags:
                      - testing
