pipeline:
  name: testing-react
  identifier: testingreact
  projectIdentifier: testing
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: github
        build: <+input>
  stages:
    - stage:
        name: buildAndPush
        identifier: buildAndPush
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          platform:
            os: Linux
            arch: Arm64
          runtime:
            type: Docker
            spec: {}
          execution:
            steps:
              - step:
                  type: BuildAndPushDockerRegistry
                  name: BuildAndPushDockerRegistry_1
                  identifier: BuildAndPushDockerRegistry_1
                  spec:
                    connectorRef: Docker_connector
                    repo: https://hub.docker.com/r/venkatasridhar/testingharness
                    tags:
                      - first-test
                    caching: true
